---
title: "Esm204_ass2"
author: "Jeremy Knox"
date: "4/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)
library(stargazer)
library(latex2exp)
library(finalfit)

gas_raw = read_csv("Gas_Data.csv")
gas = read_csv("Gas_Data.csv")
  colnames(gas) = c("Price", "Q_l", "Q_h")

```
as.numeric(mod3$coef[2])
[1] -0.01220884


```{r}
# P = Price
# Q = Quantity
# D = Demand 
# S = Supply

# Demand for Low Income:
# P = 21.99085 - (0.0001355174 * Q) 
lm_D_l = glm(Price ~ Q_l, data = gas)
D_l = function(Q) as.numeric(coef(lm_D_l)["(Intercept)"]) + Q * as.numeric(coef(lm_D_l)["Q_l"]) 

# Demand for High Income:
# P = 23.39144 - (0.0001296638 * Q)
lm_D_h = glm(Price ~ Q_h, data = gas)
D_h = function(Q) as.numeric(coef(lm_D_h)["(Intercept)"]) + Q * as.numeric(coef(lm_D_h)["Q_h"]) 

# Demand Aggregate:
# P = 22.70657 - (0.0000662629 * Q)
# In terms of Q, D_agg:= Q = 342674 - (15091.4 * P)
# At P = 5 => Q = 267217.1
D_agg = function(Q) 22.70657 - (0.0000662629 * Q)

# Market Equalibrium: 
P_equalibrium = 5
Q_equalibrium = (P_equalibrium / as.numeric(coef(lm_D_l)["Q_l"])) +
       (-as.numeric(coef(lm_D_l)["(Intercept)"]) / as.numeric(coef(lm_D_l)["Q_l"])) + 
       (P_equalibrium / as.numeric(coef(lm_D_h)["Q_h"])) + 
       (-as.numeric(coef(lm_D_h)["(Intercept)"]) / as.numeric(coef(lm_D_h)["Q_h"])) 
equalibrium = data.frame(P_equalibrium, Q_equalibrium)

# Supply:
# P = 0 + ((267217.1 / 5) * Q)
S = function(Q) (equalibrium$Q_equalibrium / equalibrium$p_equalibrium * Q)

figure1 = ggplot(data = data.frame(x = 0), mapping = aes(x = x)) +
  stat_function(fun = S) + 
  stat_function(fun = D_h) +
  stat_function(fun = D_l) +
  stat_function(fun = D_agg) +
  geom_point(aes(x = equalibrium$Q_equalibrium, 
                 y = equalibrium$P_equalibrium), size = 2) +
  xlim(0, 500000) +
  ylim(0,30) +
  theme_classic()
figure1





# D_agg = function(Q) {
#   P = 29.06746 + Q * -0.0001117683 + Q * -7.864067e-05
#   return(P)
# }
# 
# S = function(Q) {
#   P = 0 + Q * (5 / 126399)
#   return(P)
# }

# Given P = 5 => Q = 126399
# curve((D_agg(x)), from = 0, to = 150000)
# curve((S(x)), from = 0, to = 150000)


# plot(c(gas$Q_h, gas$Q_l), c(gas$Price,gas$Price), xlim = c(70000, 150000))

# +plot(gas$Q_h, gas$Price, xlim = c(70000, 150000)) + 
#   plot((gas$Q_h + gas$Q_l), gas$Price, xlim = c(70000, 150000))
```

